# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: "ubuntu-16.04"
  steps:
  - task: CMake@1
    inputs:
      cmakeArgs: -G "Unix Makefiles"
    displayName: "Run CMake"
  - script: |
      pushd build > /dev/null
      make
      popd > /dev/null
    displayName: "Run Makefiles"
- job: Windows
  pool:
    vmImage: "windows-2019"
  steps:
  - task: CMake@1
    inputs:
      cmakeArgs: -G "Visual Studio 15 2017"
    displayName: "Run CMake"
  - task: MSBuild@1
    inputs:
      solution: "**/*.sln"
      configuration: "debug"
    displayName: "Build C++ files"
